# This file contains the menu description (in YAML)
# Please see the example below for the sytanx (fairly simple)

---
Menu:
  _layout: 'layout2x1'
  QuickBites:
    _name: 'Quick Bites'
    _layout: 'layout3x3'
    _image: "quick_bites.jpg"

    FrenchFries:
      _name: 'French Fries'
      _image: 'french_fries.jpg'
      _price: 50.00

    Wedges:
      _name: 'Potato Wedges'
      _image: 'wedges.jpg'
      _price: 50.00

    PotatoCheese:
      _name: 'Potato Cheese Shots'
      _image: 'potato_cheese.jpg'
      _price: 50.00

    Burger:
      _name: 'Cheese Burger'
      _image: 'burger.jpg'
      _price: 50.00

    VadaPaav:
      _name: 'Vada Paav'
      _image: 'vada_paav.jpg'
      _price: 50.00

    Sandwich:
      _name: 'Cole Saw Sandwich'
      _image: 'cole_saw_sandwich.jpg'
      _price: 50.00

    VegGrilled:
      _name: 'Veg Grilled Sandwich'
      _image: 'veg_grilled_sandwich.jpg'
      _price: 50.00

    Brownie:
      _name: 'Brownie'
      _image: 'brownie.jpg'
      _price: 50.00

  Drinks:
    _image: '400x400white.png'
    _layout: 'layout2x2'

    CoffeeTea:
      _name: 'Coffee / Tea'
      _image: 'coffee_tea.jpg'
      _price: 10.00

    Mocktails:
      _name: 'Mocktails'
      _image: 'mocktails.jpg'
      _price: 15.00

    ChocolateShake:
      _name: 'Chocolate Milk Shake'
      _image: 'chocolate_milk_shake.jpg'
      _price: 20.00

  _Qty:
    _root: true
    _layout: 'layout3x3'
    _name: "Quantity"
    1:
      _image: false
    2:
      _image: false
    3:
      _image: false
    4:
      _image: false
    5:
      _image: false
    6:
      _image: false
    7:
      _image: false
    8:
      _image: false      
    9:
      _image: false
  _Add_More:
    _root: true
    _name: 'Main Menu'
    _layout: 'layout2x1'
    AddItem:
      _name: 'Add another item'
      _image: false
      _option: 'add_item'
    _ShowInvoice:
      _name: 'Show Invoice'
      _image: false
      _option: 'show'
    PrintInvoice:
      _name: 'Print and Save Invoice'
      _image: false
      _option: 'print'



