---
Menu:
  _layout: 'layout2x3'
  12_inch_plate:
    _name: 12_inch_plate
    _image: 12_inch_plate.jpg
    _audio: 12_inch_plate.wav
    _price: 20.00

  10_inch_plate:
    _name: 10_inch_plate
    _image: 10_inch_plate.jpg
    _audio: 10_inch_plate.wav
    _price: 20.00
  4_inch_saucer:
    _name: 4_inch_saucer
    _image: 4_inch_saucer.jpg
    _audio: 4_inch_saucer.wav
    _price: 20.00
  8_by_7_inch_plate:
    _name: 8_by_7_inch_plate
    _image: 8_by_7_inch_plate.jpg
    _audio: 8_by_7_inch_plate.wav
    _price: 20.00
  3_inch_cup:
    _name: 3_inch_cup
    _image: 3_inch_cup.jpg
    _audio: 3_inch_cup.wav
    _price: 20.00




  _Qty:
    _root: true
    _layout: 'layout3x3'
    _name: "Quantity"
    1:
      _image: false
      _audio: 'one.wav'
    2:
      _image: false
      _audio: 'two.wav'
    3:
      _image: false
      _audio: 'three.wav'
    4:
      _image: false
      _audio: 'four.wav'
    5:
      _image: false
      _audio: 'five.wav'
    6:
      _image: false
      _audio: 'six.wav'
    7:
      _image: false
      _audio: 'seven.wav'
    8:
      _image: false      
      _audio: 'eight.wav'
    9:
      _image: false
      _audio: 'nine.wav'
  _Add_More:
    _root: true
    _name: 'Main Menu'
    _layout: 'layout2x1'
    AddItem:
      _name: 'Add another item'
      _image: false
      _audio: 'add_more_items.wav'
      _option: 'add_item'
    _ShowInvoice:
      _name: 'Show Invoice'
      _image: false
      _option: 'show'
    PrintInvoice:
      _name: 'Print and Save Bill'
      _image: false
      _audio: 'print_bill.wav'
      _option: 'print'
