# This file contains the menu description (in YAML)
# Please see the example below for the sytanx (fairly simple)

---
Menu:
  _layout: 'layout2x1'
  QuickBites:
    _name: 'Quick Bites'
    _layout: 'layout3x3'
    _image: "quick_bites.jpg" 
    _audio: 'quick_bites.wav'  

    FrenchFries:
      _name: 'French Fries'
      _image: 'french_fries.jpg'
      _price: 50.00
      _audio: 'french_fries.wav'

    Wedges:
      _name: 'Potato Wedges'
      _image: 'wedges.jpg'
      _price: 50.00
      _audio: 'potato_wedges.wav'

    PotatoCheese:
      _name: 'Potato Cheese Shots'
      _image: 'potato_cheese.jpg'
      _price: 50.00
      _audio: 'potato_cheese_shots.wav'

    Burger:
      _name: 'Cheese Burger'
      _image: 'burger.jpg'
      _price: 50.00
      _audio: false        

    VadaPaav:
      _name: 'Vada Paav'
      _image: 'vada_paav.jpg'
      _price: 50.00
      _audio: 'vada_paav.wav'

    Sandwich:
      _name: 'Cole Saw Sandwich'
      _image: 'cole_saw_sandwich.jpg'
      _price: 50.00
      _audio: 'cole_saw_sandwich.wav'

    VegGrilled:
      _name: 'Veg Grilled Sandwich'
      _image: 'veg_grilled_sandwich.jpg'
      _price: 50.00
      _audio: 'grilled_vegetable_sandwich.wav'

    Brownie:
      _name: 'Brownie'
      _image: 'brownie.jpg'
      _price: 50.00
      _audio: 'desserts.wav'

  Drinks:
    _image: '400x400white.png'
    _layout: 'layout2x2' 
    _audio: 'drinks.wav'   

    CoffeeTea:
      _name: 'Coffee / Tea'
      _image: 'coffee_tea.jpg'
      _price: 10.00
      _audio: 'tea.wav'

    Mocktails:
      _name: 'Mocktails'
      _image: 'mocktails.jpg'
      _price: 15.00
      _audio: 'mocktails.wav'

    ChocolateShake:
      _name: 'Chocolate Milk Shake'
      _image: 'chocolate_milk_shake.jpg'
      _price: 20.00
      _audio: 'chocolate_milk_shake.wav'

  _Qty:
    _root: true
    _layout: 'layout3x3'
    _name: "Quantity"
    1:
      _image: false
      _audio: 'one.wav'
    2:
      _image: false
      _audio: 'two.wav'
    3:
      _image: false
      _audio: 'three.wav'
    4:
      _image: false
      _audio: 'four.wav'
    5:
      _image: false
      _audio: 'five.wav'
    6:
      _image: false
      _audio: 'six.wav'
    7:
      _image: false
      _audio: 'seven.wav'
    8:
      _image: false      
      _audio: 'eight.wav'
    9:
      _image: false
      _audio: 'nine.wav'
  _Add_More:
    _root: true
    _name: 'Main Menu'
    _layout: 'layout2x1'
    AddItem:
      _name: 'Add another item'
      _image: false
      _audio: 'add_more_items.wav'
      _option: 'add_item'
    _ShowInvoice:
      _name: 'Show Invoice'
      _image: false
      _option: 'show'
    PrintInvoice:
      _name: 'Print and Save Bill'
      _image: false
      _audio: 'print_bill.wav'
      _option: 'print'



